backend:
  name: github
  repo: Emad492/Emad-Adel-Ali.github.io
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "homepage"
    label: "Homepage"
    files:
      - label: "Home Content"
        name: "home"
        file: "index.html"
        fields:
          - { label: "Name", name: "name", widget: "string" }
          - { label: "Job Title", name: "title", widget: "string" }
          - { label: "LinkedIn", name: "linkedin", widget: "string" }
          - { label: "CV Link", name: "cv", widget: "string" }