backend:
  name: github
  repo: "emad-adel-ali/emad-adel-ali.github.io"
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "siteinfo"
    label: "Site Info"
    files:
      - file: "data/info.yml"
        label: "Site Info"
        name: "info"
        fields:
          - label: "Name"
            name: "name"
            widget: "string"
          - label: "Job Title"
            name: "title"
            widget: "string"
          - label: "Bio"
            name: "bio"
            widget: "text"
          - label: "LinkedIn URL"
            name: "linkedin"
            widget: "string"
          - label: "CV File Path"
            name: "cv"
            widget: "string"
